server:
  port: 80
  
spring:
  redis:
    host: 116.62.187.190
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
logging:
  level:
    org.springframework: info

security:
    oauth2:
      storeType: redis #或者jwt
      jwtSigningKey: yangguang
      clients[0]:
        clientId: yangguang
        clientSecret: YG2018
      clients[1]:
              clientId: grassroot1
              clientSecret: grassroot1
